# Build file for AWS CodeBuild thats is used in one service AWS Elastic Beanstalk
version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - docker login –u User –p $LOGIN_PASSWORD
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

# reports:
#   arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#     files:
#       - "**/*"
#     base-directory: 'target/tests/reports'
#     discard-paths: no
#   reportGroupCucumberJson:
#     files:
#       - 'cucumber/target/cucumber-tests.xml'
#     discard-paths: yes
#     file-format: CucumberJson # default is JunitXml
artifacts:
  files:
    - target/LogframeLab-server-1.0.0-SNAPSHOT.jar
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - target/LogframeLab-server-1.0.0-SNAPSHOT.jar
      discard-paths: yes
    artifact2:
      files:
        - target/LogframeLab-server-1.0.0-SNAPSHOT.jar
      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

# version: 0.2
# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - echo $AWS_DEFAULT_REGION
#       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
#       - echo $REPOSITORY_URI
#       - aws --version
#       - aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email
#       - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
#       - REPOSITORY_URI=015389403723.dkr.ecr.us-east-1.amazonaws.com/sample-springboot
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Build started on `date`
#       - mvn package
#       - echo Building the Docker image...
#       - docker build -t $REPOSITORY_URI:latest .
#       - echo Tagging Docker image...
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:$IMAGE_TAG