version: '3'

services:

  # Spring-Boot application
  app:
    container_name: logframelab-server
    image: logframelab-server-image
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/arqaam?autoReconnect=true&useSSL=false
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - db
      - phpmyadmin
    networks:
      - logframelab_network

  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arqaam
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - logframelab_network

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8082:80
    networks:
      - logframelab_network
networks:
  logframelab_network:
    external:
      name: logframelab_network